### ISSUE TITLE
Impossible to use infinite rentention

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/influxdb_v2_ynh#3]
When entering `0` in the "retention" field before installation (as allowed in the docs: https://docs.influxdata.com/influxdb/v2/reference/cli/influx/bucket/create/)

The installation fails and I get this message in the logs:

```
Invalid retention value. It should be a number followed by a duration unit (ns, u, µ, ms, s, m, h, d, w).
```

**Comment by M3t4Data** [comment]
Hello,
thank you for the report. The script should now accept a 0 retention value as intended.
